services:

  mysql:
    image: mysql:8.4
    container_name: administrativo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - administrativo-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  eureka:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - administrativo-net

  autenticacion:
    build:
      context: ./autenticacion
      dockerfile: Dockerfile
    container_name: autenticacion
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net

  trabajadores:
    build:
      context: ./trabajadores
      dockerfile: Dockerfile
    container_name: trabajadores
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net

  turno:
    build:
      context: ./turnos
      dockerfile: Dockerfile
    container_name: turnos
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
      trabajadores:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net
  asistencia:
    build:
      context: ./asistencia
      dockerfile: Dockerfile
    container_name: asistencia
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
      trabajadores:
        condition: service_started
      turno:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net

  bono:
    build:
      context: ./bono
      dockerfile: Dockerfile
    container_name: bono
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
      trabajadores:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net

  licencia:
    build:
      context: ./licencia
      dockerfile: Dockerfile
    container_name: licencia
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
      trabajadores:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net
  nomina:
    build:
      context: ./nominaPago
      dockerfile: Dockerfile
    container_name: nomina
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
      trabajadores:
        condition: service_started
      bono:
        condition: service_started
      licencia:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net
  notificacion:
    build:
      context: ./notificaciones
      dockerfile: Dockerfile
    container_name: notificaciones
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eureka:
        condition: service_started
      licencia:
        condition: service_started
      bono:
        condition: service_started
      nomina:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8060:8060"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      eureka:
        condition: service_started
      autenticacion:
        condition: service_started
      trabajadores:
        condition: service_started
      turno:
        condition: service_started
      asistencia:
        condition: service_started
      bono:
        condition: service_started
      licencia:
        condition: service_started
      nomina:
        condition: service_started
      notificacion:
        condition: service_started
    restart: on-failure
    networks:
      - administrativo-net

networks:
  administrativo-net:
    driver: bridge
volumes:
  mysql-data:
