CREATE DATABASE IF NOT EXISTS autenticacion;
CREATE DATABASE IF NOT EXISTS historial;
CREATE DATABASE IF NOT EXISTS turnos;
CREATE DATABASE IF NOT EXISTS asistencia;
CREATE DATABASE IF NOT EXISTS bono;
CREATE DATABASE IF NOT EXISTS licencia;
CREATE DATABASE IF NOT EXISTS nominaPago;
CREATE DATABASE IF NOT EXISTS notificacion;


