spring.application.name=asistencia

server.port = 8083

spring.datasource.url = jdbc:mysql://mysql:3306/asistencia
spring.datasource.username= root
spring.datasource.password= root
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql = true

# SWAGGER OPEN API.
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#Eureka
eureka.client.register-with-eureka = true
eureka.client.fetch-registry = true
eureka.client.service-url.defaultZone = http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address = true
